#include "subnetquiz.h"

#include <QApplication>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    SubnetQuiz w;
    a.setStyleSheet(
        "QWidget {"
        "    background-color: #1e1e2e;"
        "    color: #cdd6f4;"
        "    font-family: 'Segoe UI', Arial, sans-serif;"
        "    font-size: 14px;"
        "}"
        ""
        "QLabel {"
        "    color: #cdd6f4;"
        "}"
        ""
        "QLabel#scoreTrackerLabel {"
        "    color: #cdd6f4;"
        "    font-weight: bold;"
        "}"
        ""
        "QLabel#questionLabel {"
        "    font-size: 18px;"
        "    font-weight: bold;"
        "    color: #89b4fa;"
        "    margin: 15px 0px;"
        "}"
        ""
        "QLineEdit {"
        "    background-color: #313244;"
        "    border: 2px solid #45475a;"
        "    border-radius: 6px;"
        "    padding: 8px 12px;"
        "    font-size: 18px;"
        "    font-weight: bold;"
        "    color: #a6e3a1;"
        "    selection-background-color: #585b70;"
        "}"
        "QLineEdit:focus {"
        "    border: 2px solid #89b4fa;"
        "}"
        "QLineEdit:disabled {"
        "    background-color: #181825;"
        "    color: #585b70;"
        "    border-color: #1e1e2e;"
        "}"
        ""
        "QPushButton {"
        "    background-color: #89b4fa;"
        "    color: #11111b;"
        "    border: none;"
        "    border-radius: 6px;"
        "    padding: 10px 20px;"
        "    font-weight: bold;"
        "    font-size: 14px;"
        "}"
        "QPushButton:hover {"
        "    background-color: #b4befe;"
        "}"
        "QPushButton:pressed {"
        "    background-color: #74c7ec;"
        "}"
        ""
        "QPushButton#playAgainButton {"
        "    background-color: #a6e3a1;"
        "    color: #11111b;"
        "}"
        "QPushButton#playAgainButton:hover {"
        "    background-color: #94e2d5;"
        "}"

        );
    w.show();
    return a.exec();
}
